### ISSUE TITLE
Question regarding configuring sharp via options object

### ISSUE THREAD

**Issue by thasmo** [vseventer/sharp-image-loader#4]
In https://github.com/vseventer/sharp-image-loader/blob/master/index.js#L51 you set the manipulation instructions using a single `options` object. Skimming through the `sharp` docs, I can't seem to find any information about this type of configuration possibility.

Do I miss something or is it possible to just pass manipulation instructions options usin a single object?

Thanks a lot!

**Comment by andrewbridge** [comment]
Well aware this is probably two years too late, but just to provide some sort of info for anyone searching in the future: This seems to be relying on an undocumented characteristic of Sharp rather than adding any new layer of abstraction from the library.

The [Sharp constructor module](https://github.com/lovell/sharp/blob/master/lib/constructor.js#L125) features the same list of options as listed in this repo. A cursory look appears to show Sharp updating this single object of options using each modules own chaining methods (such as the [`jpeg` method](https://github.com/lovell/sharp/blob/master/lib/output.js#L203)).

The naming roughly aligns with the chaining methods you would call, and in turn the documentation for each option is there. For example, `.jpeg({ quality: 80 })` is the same as setting `{ jpegQuality: 80 }` with this loader.

**Comment by vseventer** [comment]
Thanks for your comment! This was originally a lazy approach from me when I really needed to manipulate my images in webpack, and couldn't find another loader allowing this.

I never got around implementing a proper API / bridge between the loader and sharp, if that's something people are interested in feel free to open another issue. Closing this one since it's pretty old.
